when:
  - event: pull_request

steps:
  - name: build-and-test
    image: rust:slim-trixie
    commands:
      - rustc --version
      - cargo --version
      - cargo clippy
      - cargo fmt --check
      - cargo build --locked --verbose
      - cargo test --locked --verbose

  - name: auto-merge-dependabot
    depends_on: [build-and-test]
    image: ghcr.io/cli/cli:latest
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - gh pr merge "$CI_COMMIT_PULL_REQUEST" --repo "$CI_REPO" --merge --delete-branch
    when:
      - event: pull_request
      - evaluate: 'CI_PIPELINE_AUTHOR == "dependabot[bot]"'